name: Auto Update dist/index.js

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'dist/**'
      - '*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          check-latest: true

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: pnpm run build

      - name: Upload dist/index.js to GitHub Repository
        run: |
          git clone https://github-action:${{ secrets.GITHUB_TOKEN }}@github.com/MZWNET/cuda-toolkit.git -b master cache
          mkdir -p cache/dist
          rm -rf cache/dist/index.js
          cp dist/index.js cache/dist/index.js
          cp dist/index.js.map cache/dist/index.js.map
          cd cache
          if ! git diff --quiet HEAD -- dist/index.js; then
            echo "dist/index.js has changes."
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions Bot"
            git status
            git add dist/index.js dist/index.js.map
            git commit -m "feat: update dist/index.js"
            git push origin master
          else
            echo "No changes in dist/index.js."
          fi
